spring.application.name=CAIT

spring.datasource.url=jdbc:postgresql://localhost:5432/CAITDATA
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

#Cloudinary
CLOUDINARY_CLOUD_NAME=${CLOUD_NAME}
CLOUDINARY_API_KEY=${API_KEY}
CLOUDINARY_API_SECRET=${API_SECRET}

