spring.application.name=CAIT

spring.datasource.url=jdbc:postgresql://localhost:5432/CAITDATA
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update